### ISSUE TITLE
Simplify working with stacks

### ISSUE THREAD

**Issue by kevsmith** [cogcmd/aws-cfn#29]
# Goal

CloudFormation is a flexible and powerful tool for deploying infrastructure "stacks". Many teams struggle with how to best use CloudFormation because it is almost too flexible and powerful. There are many ways to describe and deploy stacks and the benefits/costs of each are not always apparent. Our goal is to provide an opinionated interface to cfn's raw capabilities not just to make it easier to use but easier to use _well_.
# Design Challenge

A cfn stack can have many inputs. Since we're attempting to automate cfn calls from chat a naive approach would be to require the user to provide all inputs when creating the stack. This quickly becomes unworkable as even small stacks can have tens of inputs. Asking the user to provide the inputs, either by typing or via aliases, is unwieldy at best and downright ludicrous at worst. Our challenge is to provide a flexible way to specify stack creation inputs that's also user-friendly.
# Solution

Our answer to this design challenge is to separate the stack specification from stack creation. This allows us to provide several additional stack specification concepts which further abstract away many low level details which otherwise obscure the user interface. We do this by combining two new concepts, default sets and stack definitions, with cfn's stack templates.
## Default Set

A default set is a named set of cfn parameters and tags. They are stored as a JSON list of key/value pairs. Users can override any key/value pair in a default set when creating a stack definition.

Example defaults object:

```json
{ 
  "parameters": {
    "Name": "webapp",
    "Ports": "80"
  },
  "tags": {
    "type": "webapp"
  }
}
```

## Stack Definition

A stack definition is the combination of a cfn stack template, one or more parameter sets, and 0 or more overrides. It provides a complete definition of a cfn stack and can be used to create a stack instance.

Example definition object:

```yaml

---
name: warehouse
template:
  name: container_app
  sha: a1234f
template_url: https://s3.amazonaws.com/bucket/prefix/definitions/warehouse/127471284811/template.yml
defaults:
- name: webapp
  sha: f4321a
  params:
    Ports: '80'
  tags: {}
overrides:
  params:
    Repo: my_repo_url
    Ports: '443'
  tags:
    Name: warehouse
# Note: params and tags are generated values from the merging of defaults
# and overrides and are suitable for use in pipelines with the stack-create
# and changeset-create commands.
params:
- Ports=443
- Repo=my_repo_url
tags:
- Name=warehouse
```

## Data Storage

Most engineering and operations teams require a canonical version of their infrastructure definitions to be stored in a VCS repository. Stack templates, default sets, and stack definitions will be stored in a git repository (creds managed via dynamic configuration). Doing so supports several common use cases such as debugging and auditing. Using git for storage does have a few implementation requirements which we'll discuss next.
### Reading templates and parameter sets

The least surprising approach to reading templates and parameter sets, and the one we'll use initially, is to perform all reads from master unless the user explicitly indicates otherwise. This means commands to list, find, view, and select templates and parameter sets will need to be aware of git commit SHAs, tags, and branches.

### Deploying Stacks

Deploying a stack with cfn requires two bits of information: the stack template (or a S3 path) and parameter values. The trick is doing so while keeping the ability to easily see what versions of a stack template and parameter sets were used to create a given cfn stack.

We can provide good traceability by embedding git versioning information as outputs inside the the stack template. This information will be embedded inside the document when the template is copied from the canonical git store to the target S3 location. 

By decoupling the stack definition from the stack creation command and making use of pipelines we can use previously defined values for stack parameters while still taking advantage of Cog's execution rules to control the inputs to stack creation.

At a high level, the process looks like this:

1. User submits a chat command to create a new stack definition.
2. cfn:definition-create reads in the specified template and default sets from the configured git repo.
3. Default sets are shallow merged into single set.
4. Any user-specified overrides are applied to the merged default set.
5. A copy of the stack template with 5 additional cfn `outputs` is created. These outputs are:
   1. Name and git sha of the template used
   2. Name and git sha of each default set used
   3. Chat user name of the requesting user
6. cfn:definition-create constructs a path using the following pattern:
   `definitions/<stack definition name>/<UTC timestamp>/`
7. cfn:definition-create writes the annotated template file (as `template.yaml`) and the definition object (as `definition.yaml`) to the Git repository under `<path>` using the path computed in 6.
8. cfn:definition-create writes the annotated template file (as `template.yaml`) and the definition object (as `definition.yaml`) to the S3 bucket `/<prefix>/<path>/` using the configured S3 bucket and prefix along with the path computed in 6.
9. User calls `cfn:definition get <name> | cfn:stack-create $name $template_url -p $params -t $tags`

#### Description

Responsible for creating a new stack definition.
#### Arguments

`definition name` required
`template name` required
#### Options

`--defaults`, `-d` Ordered list of default sets to use
`--params`, `-p` Stack parameters (overrides default sets)
`--tags`, `-t` Stack tags (overrides default sets)
`--branch`, `-b` Name of git branch to use; Defaults to "master"

#### Required Permissions
`cfn:definition-create`

### Example Invocations

`cfn:definition create warehouse container_app --defaults webapp -p Ports=443 -t Name=warehouse`

Returns a definition object as shown above.

#### Description

Returns a stack definition object which may be used to create or update a stack.

#### Arguments

`definition name` required
#### Options
`--branch`, `-b` Name of git branch to use; Defaults to master
`--tag`, `-t` Name of git tag to use
`--sha`, `-s` Git commit SHA

_Note: Options are mutually exclusive._

#### Example Invocations

`cfn:definition get flywheel`

Returns a definition object as shown above.

### Description

Lists all definitions matching a pattern
#### Arguments

`name pattern` optional; defaults to `*`
#### Options

`--branch`, `-b` Name of git branch to use; Defaults to master
`--tag`, `-t` Name of git tag to use
`--sha`, `-s` Git commit SHA

_Note: Options are mutually exclusive._
#### Required Permissions

None
#### Example Invocations

`cfn:definition ls`
`cfn:definition ls --branch=dev`
`cfn:definition ls -t 1.3.4`
`cfn:definition ls web* --branch=prod`

#### Description

Responsible for creating a new default set.
#### Arguments

`default set name` required
#### Options

`--branch`, `-b` Name of git branch to use; Defaults to "master"
#### Required Permissions

`cfn:defaults-create`
#### Example Invocations

`seed ... | cfn:defaults create corp-site`
`seed ... | cfn:defaults create corp-site --b kevsmith/testing`
### Description

Lists all default sets matching a pattern
#### Arguments

`name pattern` optional; defaults to `*`
#### Options

`--branch`, `-b` Name of git branch to use; Defaults to master
`--tag`, `-t` Name of git tag to use
`--sha`, `-s` Git commit SHA

_Note: Options are mutually exclusive._
#### Required Permissions

None
#### Example Invocations

`cfn:defaults ls`
`cfn:defaults ls --branch=dev`
`cfn:defaults ls -t 1.3.4`
`cfn:defaults ls web* --branch=prod`
#### Description

Displays the contents of a default set
#### Arguments

`default set name` required; No globbing
#### Options

`--branch`, `-b` Name of git branch to use; Defaults to master
`--tag`, `-t` Name of git tag to use
`--sha`, `-s` Git commit SHA

_Note: Options are mutually exclusive._
#### Required Permissions

`cfn:defaults-show`
#### Example Invocations

`cfn:defaults show corp-site`
`cfn:defaults show corp-site --branch=prod`
### Description

Lists all cfn template matching a pattern
#### Arguments

`name pattern` optional; defaults to `*`
#### Options

`--branch`, `-b` Name of git branch to use; Defaults to master
`--tag`, `-t` Name of git tag to use
`--sha`, `-s` Git commit SHA

_Note: Options are mutually exclusive._
#### Required Permissions

None
#### Example Invocations

`cfn:template ls`
`cfn:template ls --branch=dev`
`cfn:template ls -t 1.3.4`
`cfn:template ls web* --branch=prod`
#### Description

Displays the contents of template
#### Arguments

`template name` required; No globbing
#### Options

`--branch`, `-b` Name of git branch to use; Defaults to master
`--tag`, `-t` Name of git tag to use
`--sha`, `-s` Git commit SHA

_Note: Options are mutually exclusive._
#### Required Permissions

`cfn:template-show`
#### Example Invocations

`cfn:template show corp-site`
`cfn:template show corp-site --branch=prod`
#### Description

Provides information about the backing git repository
#### Arguments

None
#### Options

`--remote`, `-r` Display remote git repo URL
`--branches`, `-b` List branches
`--tags`, `-t` List tags; Defaults to false

_Note: When no options are provided the command defaults to `--remote --branches`_.
#### Required Permissions

None
#### Example Invocations

`cfn:repo --remote`
`cfn:repo -t -r`

**Comment by vanstee** [comment]
I had a few questions as I was researching and started to build out some of the params stuff. Feel free to assume I'm misunderstanding the workflow and/or cfn since I'm pretty new to how this should work and don't have any real world experience with it outside of just testing things.

* What's the usecase for splitting out param sets from the templates? I can see
  how basic params could be reusable, but once you get into param references it
  seems like this is going to get confusing or require a validation layer?
  Should templates also include required param references for instance?

* If I understand `params-create` correctly, this will apply a commit to the
  git repo adding the new json file containing params. Is there any reason you
  would create a template using git, but then create the params from chat?

* Also related to the above, I'm guessing we should do a ff-only push and error
  on any conflicts. Is that smart enough for now?

* The stack creation command will need to change a bit; how is this for an
  exmaple? `stack-create flywheel -p phoenix-web -p pql-client -o region=us-west-1 -o name=web-4`
  I think I'll still need some help understanding how this works here.

* Here's a list of env vars I was thinking we'd need. Am I missing anything?
  GIT_REMOTE_URL
  GIT_SSH_KEY
  GIT_HTTPS_USERNAME
  GIT_HTTPS_PASSWORD
  AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY
  AWS_REGION
  S3_STACK_DEFINITON_BUCKET

* Nested stacks and stack changesets both seem useful. Are we skipping those for now?

* There's a decent amout of setup here. How can a user be sure they've set
  everything up correctly? `cfn:repo` could be used to validate repo setup, but
  it might be nice to add another `cfn:check-setup` type command to make sure
  everything is authing correctly and things are where we expect them to be.

**Comment by imbriaco** [comment]
There are some issues with the design spec above that I managed to overlook even though I read it multiple times. In particular, we need to manage **stack definitions** as top level objects and use those as input for the `cfn:stack create` and `cfn:changeset create` commands. I'll follow up on that in the next comment after this one. 

Answers to the other questions are below:

* **Templates / Params**

    Most templates will have a number of parameters defined within them, which may or may not have useful defaults. Think of parameters as being a named set of alternate default values for those parameters. For instance, I might have an `ContainerizedApplication` template that knows how to setup the environment for an ECS backed command, creates task definitions and services, etc. Then maybe I have a set of parameters called `webapp` that can be combined with `ContainerizedApplication` to specify which ports should be open, where logs should be written, and the like. And maybe I have another set called `stateful-app` that has some configuration for mounting volumes.

    This is a completely contrived example, but the basic idea is that the `param` separation gives you a place to define reusable, named defaults that can be used when instantiating a stack from a template.

* **Chat-based Param Creation**

    The idea there is just that you can define a new set of params from chat, but that they get stored in the canonical store (i.e. the git repo). You could also create a set of params manually by adding a JSON file to the right path in the repo.

    The reason you wouldn't do this with a template is just one of scope. CloudFormation templates are much more complex than a simple key/value mapping of parameters.

* Yep, ff-only push with error is perfectly fine. Also, the first step of any of the commands that interacts with Git should probably be to do a clone or reset+pull.

* **Configuration:**

    The AWS related ones are already defined for the cfn bundle so let's just talk in terms of changes. 

    The Git related configuration makes sense. We reduce the number of variables if we wanted to force username and password to be included in the URL for https backed repos instead of breaking them into their own variables, e.g. `https://user:password@github.com/my/repo`. I don't feel strongly one way or another.

    Aside from Git, we need an S3 bucket and prefix within that bucket to use as the root. We can define that as two separate variables or as an `s3://bucket/prefix/` variable. Again, no strong feeling there. The reason for the prefix is that AWS has a limit on buckets per account and we don't want to mandate that a new bucket is used if the user would rather use a path in an existing bucket.

    This should probably replace the `CFN_TEMPLATE_URL` and `CFN_POLICY_URL` and we can assume a `policies/` subdirectory under the root prefix for a policies.

* **Setup Validation**

    Having a single command to validate as much of the configuration as it can makes good sense to me. Good idea.

**Comment by imbriaco** [comment]
Stack definitions are created in terms of a template, a set of default parameters, and override parameters:

For example: 

```
cfn:definition create warehouse container_app --defaults webapp -p Ports=443 -t Name=warehouse
```

might return:

```
{ 
  "name": "warehouse",
  "template": {
    "name": "container_app",
    "sha": "a1234f"
  },
  "defaults": {
    "name": "webapp",
    "sha": "f4321a",
    "params": {
      "Ports": "80"
    },
    "tags": {}
  },
  "overrides": {
    "params": {
      "Repo": "my_repo_url",
      "Ports": "443"
    },
    "tags": {
      "Name": "warehouse"
    },
    "params": [ "Ports=443", "Repo=my_repo_url" ],
    "tags": [ "Name=warehouse" ]
  }
```

This same output would be returned by `cfn:definition get` and could be used as input for `cfn:stack create` or `cfn:changeset create` like so:

```
cfn:definition get warehouse | cfn:stack create $name $template.name --p $params -t $tags
cfn:definition get warehouse | cfn:changeset create $name --template $template.name -p $params -t $tags
```

The reason we want to decouple these is so that we can apply permissions to the inputs to `stack create` and `changeset create` through execution rules. If the merge happened within the stack and changeset commands, those parameter values would be opaque to Cog's access control system.

We should write these definitions to the Git repo as `defintions/<name>/<timestamp>.yaml`.

**Comment by vanstee** [comment]
* Templates/Params

The only part I'm still missing here is, how do you know which params and templates should be used together. For instance let's say the `ContainerizedApplication` template defines a ref to a `WebAppPort` in the `webapp` param set. How do I know that the `ContainerizedApplication` template should be used with the `webapp` param set? Is this just something that I'll have to look at the template and the param sets to figure out manually? Do we intend to have a command to "find the param set that defines the `WebAppPort` param"? I might just be overthinking how these are used together.

* Chat-based Param Creation

Makes sense. And yep, I'm in the process of switching to using `rugged` to clone the repo each time a command requiring access to the git repo is run. We might be able to improve this eventually, but this should work for now.

* Configuration

I'll just punt on making this super configurable. Let's stick to `GIT_REMOTE_URL` and `GIT_SSH_KEY` instead of having username and password env vars. Also I'll add an s3 prefix env var. Thanks :+1:

* Setup Validation

Will do.

**Comment by imbriaco** [comment]
* **Templates/Params**

    I think we can get by without being prescriptive at first, but this is a good thought for a future revision. As long as we put parameters and tags each under their own top-level key we could add a `templates: [ ... ]` key later that lists the templates this set of defaults is valid for. Also, let's call these `defaults` instead of `params` since they also _contain_ parameters. I'll update the definition that Kevin posted accordingly.

**Comment by imbriaco** [comment]
This is completed in `aws-cfn` 0.5.0 and later.
